### ISSUE TITLE
Fresh install doesn't build

### ISSUE THREAD

**Issue by keaglin** [payloadcms/nextjs-custom-server#14]
Problem:
<img width="797" alt="Screen Shot 2022-06-02 at 11 13 49 PM" src="https://user-images.githubusercontent.com/1952896/171971037-05987ce9-aaa3-40f4-b8e1-6dd766ff0a0f.png">

My computer: M1 Mac Mini on macOS 12.4

Steps to reproduce:
1. Start a project with this template
2. Install dependencies (I used `yarn`)
3. `yarn build` (or `npm run build`)
4. Result above

I had this issue earlier and thought it might've been some code I added so I did some more digging and eventually just cloned a fresh copy to try and still got this issue.
I considered maybe it was me using too new a node version (18) so I tried the latest of v16 and v14 but all ended the same. 

I also ran into the issue below. Following their recommendation seemed to fix it. Something to be aware of though.
<img width="1095" alt="Screen Shot 2022-06-03 at 9 38 31 PM" src="https://user-images.githubusercontent.com/1952896/171971617-9acc8300-6817-4341-8bb6-6b77e5212839.png">

**Comment by chrisandrew-dev** [comment]
I have a similar issue with a different error message. 

**Computer:**
Macbook Air (M1)
macOS Monterey v12.4

**Node version:**
18.2.0

**Steps to reproduce:**
1. Create a project from this template
2. Run `yarn` command (or `npm install`)

**Error details:**
```
...
error /Users/chris/websites/vivo/vivo-digital/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
...
make: *** [Release/sass.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
```

**Troubleshooting**
- Rebuilding node-sass did not resolve the issue.
- Deleting node_modules and reinstalling packages did not resolve the issue
- Using an earlier version of node.js did not resolve the issue
- Using NPM versus Yarn did not resolve the issue

**Comment by DanRibbens** [comment]
Closing with changes https://github.com/payloadcms/nextjs-custom-server/pull/15.

Please reopen if problems persist.
