### ISSUE TITLE
Slate error

### ISSUE THREAD

**Issue by CelsoMMiranda** [payloadcms/nextjs-custom-server#17]
Hi, trying to use the example provided, I'm facing the issue when clicking on add new block, and then on content.
Uncaught Error: [Slate] editor is invalid! you passed:{"children":[],"operations":[],"selection":null,"marks":null,"history":{"undos":[],"redos":[]}}

**Comment by benjchan** [comment]
I'm getting the same issue. A blank screen and that error when clicking on any block type.

Edit: It seems the issue likes with the just the rich text editor field. Removing that from the blocks makes the layouts work correctly.

**Comment by mikemoooo** [comment]
Hey! I was facing the same problem whith this project.
Together with @jmikrut we identified the problem.
For your nextjs part of the project you need to use the same version of slate as payload uses internally.
At this moment that is: `"slate": "0.72.8",`
Changing the version solved the issue for me. Hope it helps you, too!

**Comment by denolfe** [comment]
Thanks for posting the solution @mikemoooo.
