### ISSUE TITLE
TypeError: children.map is not a function

### ISSUE THREAD

**Issue by samp-reston** [payloadcms/nextjs-custom-server#18]
```
TypeError: children.map is not a function
  18 | }
  19 | 
> 20 | const serialize = (children: Children): React.ReactElement[] => children.map((node, i) => {
     |                                                                         ^
  21 |   if (Text.isText(node)) {
  22 |     let text = <span dangerouslySetInnerHTML={{ __html: escapeHTML(node.text) }} />;
  23 | 
```

**Comment by denolfe** [comment]
Hey @samp-reston , could you provide some more context? How did you receive this error? How can we recreate it?

**Comment by samp-reston** [comment]
> Hey @samp-reston , could you provide some more context? How did you receive this error? How can we recreate it?

Yeah sorry, I cloned the repo, ran `npm i` and then `npm run dev`. Then the error occurred. I actually deleted the repo afterwards, and just cloned it again today, and the issue came up again.

I'm running Windows 10, Node v16.16.0, npm v8.11.0

**Comment by DanRibbens** [comment]
@samp-reston Did you run the seed function after you installed dependencies?
https://github.com/payloadcms/nextjs-custom-server/blob/3ab766daac8abf0e53393c3ee6aa4a5a0ff7816a/package.json#L19

I think you just missed a step. We should update the installation steps in the readme, currently `seed` and `dev` are out of order.

**Comment by samp-reston** [comment]
@DanRibbens Perfect that fixed it, I assumed it was _optional_ so I didn't do that. I'm not familiar with seeding so didn't think of it. Many thanks! 😄

**Comment by DanRibbens** [comment]
> @DanRibbens Perfect that fixed it, I assumed it was _optional_ so I didn't do that. I'm not familiar with seeding so didn't think of it. Many thanks! 😄

You're welcome, yeah it is a little confusing in how the readme is written. As you said "optional" is misleading as it is either run the script to create the data or enter data into the CMS first. Some things we should do to improve this:

1. better handling of missing data
2. update the readme to be more clear about seeding or entering data to begin

Thanks for asking about it!
