### ISSUE TITLE
How do i hosy this on ec2

### ISSUE THREAD

**Issue by SyedMuzamilM** [payloadcms/nextjs-custom-server#20]
I want to host this on ec2 but I am not able to host it properly. Can you help me with that.

**Comment by SyedMuzamilM** [comment]
I was able to host the website  and used nginx as the server. Now I am able to access the website but not the admin part

**Comment by JarrodMFlesch** [comment]
@SyedMuzamilM did you get this figured out?

**Comment by SyedMuzamilM** [comment]
@JarrodMFlesch Yes.
