### ISSUE TITLE
admin route results in blank page

### ISSUE THREAD

**Issue by zaunermax** [payloadcms/nextjs-custom-server#3]
I noticed, that [this line ](https://github.com/payloadcms/nextjs-custom-server/blob/e9e55624ab7b8838c42423312a7e59f9b1b07d1e/payload.config.ts#L9)causes an error when opening the admin interface, somehow the left side is resolved as the string, so after the tranpilation the resulting code is something along the lines of this:
```
'http://localhost:3000' = process.env.SERVER_URL;
process.env.NEXT_PUBLIC_SERVER_URL = process.env.SERVER_URL;
```
which produces an error and a white page on `localhost:3000/admin`
![image](https://user-images.githubusercontent.com/15246773/108083135-0e654580-7073-11eb-9335-301a4c2f9ed5.png)

**Comment by DanRibbens** [comment]
I was trying to be clever by assigning the env var server urls in one place so that both seed and server would work. I failed to realize it can't be assigned there because of webpack. 

This should be fixed now. Thanks for reporting the issue!
