### ISSUE TITLE
` Detected multiple renderers` warning when upgrading to new `app` directory

### ISSUE THREAD

**Issue by gabrielkuettel** [payloadcms/nextjs-custom-server#35]
I'm getting the following warning when switching over to the new `app` directory:

`Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.`

Any ideas on what could be causing this?

**Comment by jacobsfletch** [comment]
Hey @gabrielkuettel! Hmm what is your setup? I just opened a PR in the Payload main repo with a fully working example of how to achieve this using the new Next.js App Router. Check it out! https://github.com/payloadcms/payload/pull/2920

I'm curious what differences there might be between that PR and your current setup. If you could provide some more details I'd be happy to help!

**Comment by jacobsfletch** [comment]
Hey @gabrielkuettel! Check out my latest comment on another issue here: https://github.com/payloadcms/nextjs-custom-server/issues/23#issuecomment-1624323948

> Hey everyone! This repo has officially moved to the examples directory here: https://github.com/payloadcms/payload/tree/master/examples/custom-server and so it will be archived shortly. This new example is using the new Next.js 13 App Router, so I'm going to go ahead and close this issue. If you're still having troubles, take a look through that new example. Let me know if you're still having troubles after that, I'll be happy to help 👍

Let me know if you need anything here and I'd be happy to give you a hand.
