### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by Harrizontal** [payloadcms/nextjs-custom-server#36]
Hi all,

Just wanna spin up and try next + payload cms for my blog... but I am having dependencies issue with jest.

```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: payload-nextjs-server@0.0.1
npm ERR! Found: eslint-plugin-jest-dom@3.9.4
npm ERR! node_modules/eslint-plugin-jest-dom
npm ERR!   dev eslint-plugin-jest-dom@"^3.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-jest-dom@"^2.0.0" from @trbl/eslint-config@1.2.4
npm ERR! node_modules/@trbl/eslint-config
npm ERR!   dev @trbl/eslint-config@"^1.2.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/user1/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user1/.npm/_logs/2023-05-13T10_34_34_562Z-debug-0.log
```

Apologies in advance but I am still a beginning in web!

Many thanks :)

**Comment by jacobsfletch** [comment]
Hey @Harrizontal this should get resolved with https://github.com/payloadcms/payload/pull/2656 but in the meantime you should be able to use `npm install --save --legacy-peer-deps payload` to get past this or install with yarn `yarn install`.

**Comment by jacobsfletch** [comment]
@Harrizontal any luck here? Bump Payload to latest and try again. If you have any more issues I'd be happy to help.

**Comment by Harrizontal** [comment]
hi @jacobsfletch thanks for reaching out!

I am able to run `npx create-payload-app`, connect to a mongo db and run the project successfully! 

Thanks again, Jacob!
