### ISSUE TITLE
Server listening is delayed

### ISSUE THREAD

**Issue by thgh** [payloadcms/nextjs-custom-server#38]
server.listen() waits for the server to be ready, but this means that the browser shows the connection refused error. The server should instead listen immediately and hang until the server is ready. (as payload & next support already afaik)

https://github.com/payloadcms/nextjs-custom-server/blob/a67efef72200f74ce3e9bd94f447f5a6fbb90636/server.ts#L30

**Comment by jacobsfletch** [comment]
Hey @thgh I could not get this to work as you described to me before, but maybe you can? 🤷 Although to be honest, I haven't experienced this (I don't think) so maybe you can send me a screen recording of what you're seeing so it makes more sense to me.

Check out my latest comment on this issue: https://github.com/payloadcms/nextjs-custom-server/issues/23#issuecomment-1624323948

> Hey everyone! This repo has officially moved to the examples directory here: https://github.com/payloadcms/payload/tree/master/examples/custom-server and so it will be archived shortly. This new example is using the new Next.js 13 App Router, so I'm going to go ahead and close this issue. If you're still having troubles, take a look through that new example. Let me know if you're still having troubles after that, I'll be happy to help 👍

I'd be happy to accept a PR in the main repo for this if it's still an issue and you're willing to take it on! https://github.com/payloadcms/payload/tree/master/examples/custom-server
