### ISSUE TITLE
Compile will fail on Windows (10) - 'NODE_ENV' is not recognized

### ISSUE THREAD

**Issue by BeeWaTecANE** [payloadcms/nextjs-custom-server#7]
# Bug Report

NODE_ENV will not work on Windows. 
Error-Message: `'NODE_ENV' is not recognized as an internal or external command`

## Expected Behavior

Will compile without  problems

## Current Behavior

Error-Message on compile

## Possible Solution

1) Add cross-env
```sh
yarn add cross-env
```

2) Update build / serve step
```ts
"scripts": {
        "build:next": "next build",
        "build:server": "tsc --project tsconfig.server.json",
        "build:payload": "payload build",
        "build": "cross-env NODE_ENV=production yarn build:payload && yarn build:server && cross-env NEXT_BUILD=true node dist/index.js",
        "dev": "node server/index.js",
        "seed": "node seed/index.js",
        "serve": "cross-env NODE_ENV=production node dist/index.js"
},
```

## Steps to Reproduce
1. Clone repository on Windows 10
2. `yarn install`
3. `yarn build`

## Detailed Description

- yarn: 1.22.11

**Comment by DanRibbens** [comment]
Fixed in https://github.com/payloadcms/nextjs-custom-server/pull/15
