### ISSUE TITLE
Sharp version clash between Next and Payload when using next/image

### ISSUE THREAD

**Issue by JessRynkar** [payloadcms/nextjs-custom-server#9]
# Bug Report

Next and Payload are currently on different versions of Sharp, this breaks the next/image component when you try to use it.

## Possible Solution

Downgrade Payload Sharp to a compatible version, 0.26.3 and 0.26.3 worked when tested, 0.26.3 and 0.27.0 did also work. Not sure what to make of that.

## Steps to Reproduce
1. Checkout fix/next-image-incompatibility
2. Make sure Payload is updated 
3. Yarn dev 
4. Add image to the home page
5. Go to home page
6. Breaks

## Details

- both version 0.26.3 worked when tested
- version 0.26.3 (next) and 0.27.0 also worked when tested
- Below is screenshot of the error
<img width="737" alt="next-image-error" src="https://user-images.githubusercontent.com/67977755/136242072-4c7cea27-4a74-4f3a-88be-35172484185b.png">.

**Comment by thefrana** [comment]
@DanRibbens Why is this closed without any comment? I am having the same problem. I tried upgrading to many versions but it did not help. Even this repo suffers from the same problem.

**Comment by DanRibbens** [comment]
@lksfrn is reporting this issue again.

**Possible solution**: add slate to peerDependency with a version that works for both Payload and next/image.

**Comment by JessRynkar** [comment]
Payload has since updated to Sharp v0.31.3 and this error is no longer occurring when using next/image.
